title: Anderson Marzola - System Architect
email: ajmarzola@gmail.com
description: In this blog, my goal is more than just sharing technical knowledge. I want to create an environment for learning and exchanging experiences, covering everything from practical tips and tutorials to discussions about software architecture and technological trends.
baseurl: ""
url: "https://ajmarzola.github.io/"
twitter_username: tbn_pepe
github_username:  ajmarzola
markdown: kramdown
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Anderson Marzola
  email: ajmarzola@gmail.com
  bio: "Desenvolvedor apaixonado por tecnologia e aprendizado."
  avatar: /assets/images/avatar.png

bulma_clean_theme:
  navbar_brand: Anderson Marzola - System Architect
  navbar_links:
    - title: About
      url: /about/
    - title: Contact
      url: /contact/
  footer_text: "© 2024 Anderson Marzola - System Architect. Todos os direitos reservados."
