title: Anderson Marzola - System Architect
email: ajmarzola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  In this blog, my goal is more than just sharing technical knowledge. I want to create an environment for learning and exchanging experiences, covering everything from practical tips and tutorials to discussions about software architecture and technological trends.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ajmarzola.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tbn_pepe
github_username:  ajmarzola
markdown: kramdown

# Build settings
theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Autor
author:
  name: Anderson Marzola
  email: ajmarzola@gmail.com
  bio: "Desenvolvedor apaixonado por tecnologia e aprendizado."
  avatar: /assets/images/avatar.png

# Configurações do tema
bulma_clean_theme:
  navbar_brand: Anderson Marzola - System Architect
  navbar_links:
    - title: About
      url: /about/
    - title: Contact
      url: /contact/
  footer_text: "© 2024 Anderson Marzola - System Architect. Todos os direitos reservados."